apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-library-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /srv/redesigned-winner/games
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-library-pvc
  namespace: redesigned-winner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: game-library-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamehub-deployment
  namespace: redesigned-winner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamehub-server
  template:
    metadata:
      labels:
        app: gamehub-server
    spec:
      containers:
      - name: nginx
        image: docker.io/ipatedavid/redesigned-winner:sha-945f941
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: games
          mountPath: /app/games
      imagePullSecrets:
      - name: dockerhub-creds
      volumes:
      - name: games
        persistentVolumeClaim:
          claimName: game-library-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: gamehub-service
  namespace: redesigned-winner
spec:
  type: NodePort
  selector:
    app: gamehub-server
  ports:
    - protocol: TCP
      port: 80          # Service port inside cluster
      targetPort: 3000    # Container port
      nodePort: 30333   # External port on the node (must be 30000–32767)

